[build]
target = "wasm32-unknown-unknown"

[target.wasm32-unknown-unknown]
rustflags = [
    "-C", "link-arg=--import-memory",
    "-C", "link-arg=--initial-memory=65536",
    "-C", "link-arg=--max-memory=65536",
    "-C", "link-arg=--allow-undefined",
    "-C", "link-arg=--no-stack-first",
    "-C", "link-arg=--global-base=6592",
    "-C", "link-arg=-z",
    "-C", "link-arg=stack-size=14752",
]
