//! Roc Platform ABI
//!
//! This file defines the Zig interface for hosted functions in a Roc platform.
//! It is automatically generated by the Roc glue generator.
//!
//! Hosted argument ownership:
//! - Roc transfers ownership of refcounted arguments to the hosted function.
//! - The hosted function must decref owned refcounted arguments when done.
//! - If the host stores or returns an argument, it must retain or transfer ownership explicitly.
//!
//! Usage:
//! 1. Import this file in your platform host
//! 2. Implement each hosted function according to its signature
//! 3. Call hostedFunctions() to create the dispatch table for RocOps

const std = @import("std");
const builtin = @import("builtin");

/// Type-erased function pointer for hosted function dispatch.
///
/// Roc transfers ownership of refcounted arguments to hosted functions.
/// Hosted functions must decref owned refcounted arguments when done,
/// or transfer that ownership into the return value or longer-lived storage.
/// If the host keeps both the call argument and a stored copy, it must
/// incref the stored copy so each live reference has one ownership.
pub const HostedFn = *const fn (*anyopaque, *anyopaque, *anyopaque) callconv(.c) void;

/// Table of hosted function pointers passed to the Roc runtime.
pub const HostedFunctions = extern struct {
    count: u32,
    fns: [*]HostedFn,
};

/// Arguments for a Roc allocation request.
pub const RocAlloc = extern struct { alignment: usize, length: usize, answer: *anyopaque };
/// Arguments for a Roc deallocation request.
pub const RocDealloc = extern struct { alignment: usize, ptr: *anyopaque };
/// Arguments for a Roc reallocation request.
pub const RocRealloc = extern struct { alignment: usize, new_length: usize, answer: *anyopaque };
/// Arguments for a Roc `dbg` expression.
pub const RocDbg = extern struct { utf8_bytes: [*]u8, len: usize };
/// Arguments for a failed Roc `expect`.
pub const RocExpectFailed = extern struct { utf8_bytes: [*]u8, len: usize };
/// Arguments for a Roc `crash`.
pub const RocCrashed = extern struct { utf8_bytes: [*]u8, len: usize };

/// The operations table passed from the host to the Roc runtime.
pub const RocOps = extern struct {
    env: *anyopaque,
    roc_alloc: *const fn (*RocAlloc, *anyopaque) callconv(.c) void,
    roc_dealloc: *const fn (*RocDealloc, *anyopaque) callconv(.c) void,
    roc_realloc: *const fn (*RocRealloc, *anyopaque) callconv(.c) void,
    roc_dbg: *const fn (*const RocDbg, *anyopaque) callconv(.c) void,
    roc_expect_failed: *const fn (*const RocExpectFailed, *anyopaque) callconv(.c) void,
    roc_crashed: *const fn (*const RocCrashed, *anyopaque) callconv(.c) void,
    hosted_fns: HostedFunctions,
};

/// Uniform ABI function pointer stored in `RocErasedCallablePayload`.
pub const RocErasedCallableFn = *const fn (*RocOps, ?[*]u8, ?[*]const u8, ?[*]u8) callconv(.c) void;

/// Final-drop callback for inline erased-callable captures.
pub const RocErasedCallableOnDrop = *const fn (?[*]u8, *RocOps) callconv(.c) void;

/// Payload header for `Box(function)`.
pub const RocErasedCallablePayload = extern struct {
    callable_fn_ptr: RocErasedCallableFn,
    on_drop: ?RocErasedCallableOnDrop,
};

/// Runtime representation of `Box(function)`.
pub const RocErasedCallable = ?[*]u8;

pub const roc_erased_callable_capture_alignment: usize = 16;
pub const roc_erased_callable_payload_alignment: usize = 16;
pub const roc_erased_callable_capture_offset: usize = std.mem.alignForward(usize, @sizeOf(RocErasedCallablePayload), roc_erased_callable_capture_alignment);

pub fn rocErasedCallablePayloadSize(capture_size: usize) usize {
    return roc_erased_callable_capture_offset + capture_size;
}

pub fn rocErasedCallablePayloadPtr(callable: RocErasedCallable) *RocErasedCallablePayload {
    return @ptrCast(@alignCast(callable orelse unreachable));
}

pub fn rocErasedCallableCapturePtr(callable: RocErasedCallable) ?[*]u8 {
    const data = callable orelse return null;
    return data + roc_erased_callable_capture_offset;
}

pub fn rocErasedCallableAllocate(
    roc_ops: *RocOps,
    callable_fn_ptr: RocErasedCallableFn,
    on_drop: ?RocErasedCallableOnDrop,
    capture_size: usize,
) RocErasedCallable {
    const ptr_width = @sizeOf(usize);
    const alignment = @max(ptr_width, roc_erased_callable_payload_alignment);
    const extra_bytes = @max(ptr_width, roc_erased_callable_payload_alignment);
    var alloc_args: RocAlloc = .{
        .alignment = alignment,
        .length = extra_bytes + rocErasedCallablePayloadSize(capture_size),
        .answer = undefined,
    };
    roc_ops.roc_alloc(&alloc_args, roc_ops.env);
    const base: [*]u8 = @ptrCast(alloc_args.answer);
    const data = base + extra_bytes;
    const rc: *isize = @ptrFromInt(@intFromPtr(data) - @sizeOf(isize));
    rc.* = 1;
    const payload: *RocErasedCallablePayload = @ptrCast(@alignCast(data));
    payload.* = .{ .callable_fn_ptr = callable_fn_ptr, .on_drop = on_drop };
    return data;
}

/// Type-erase a hosted function pointer to `HostedFn`.
///
/// Hosted functions are typically written with concrete parameter types for clarity
/// (e.g. `*RocOps`, `*RocStr`, `[*]u8`), but must be stored as `HostedFn` which
/// uses `*anyopaque` for all parameters. This helper performs that cast.
pub fn hostedFn(func: anytype) HostedFn {
    const T = @TypeOf(func);
    const info = @typeInfo(T);
    if (info == .pointer) {
        const child = @typeInfo(info.pointer.child);
        if (child == .@"fn") {
            const f = child.@"fn";
            if (f.params.len != 3)
                @compileError("hostedFn: function must take exactly 3 parameters (ops, ret_ptr, args_ptr)");
            if (f.return_type != void)
                @compileError("hostedFn: function must return void");
        }
    }
    return @ptrCast(func);
}

/// A Roc string value. Small strings (up to 23 bytes) are stored inline;
/// larger strings are heap-allocated with a reference count.
///
/// `bytes` is never tagged. Operations, host code, glue code, and object-file
/// relocations can use it directly as the UTF-8 byte pointer for non-small
/// strings. Seamless-slice tagging lives in `capacity_or_alloc_ptr` instead.
/// Big-string capacity is stored shifted left by one bit, so max capacity is
/// essentially `std.math.maxInt(isize)` bytes: about 2 GiB on 32-bit targets
/// and 8 EiB on 64-bit targets.
pub const RocStr = extern struct {
    bytes: ?[*]u8,
    capacity_or_alloc_ptr: usize,
    length: usize,

    const Self = @This();
    const small_string_size = @sizeOf(RocStr);
    const small_str_max_length = small_string_size - 1;
    const small_str_bit: usize = @as(usize, @bitCast(@as(isize, std.math.minInt(isize))));
    const seamless_slice_tag: usize = 1;

    /// Return the string contents as a `[]const u8` slice.
    pub fn asSlice(self: *const Self) []const u8 {
        return self.asU8ptr()[0..self.len()];
    }

    /// Return the length of the string in bytes.
    pub fn len(self: Self) usize {
        if (self.isSmallStr()) {
            return @as([*]const u8, @ptrCast(&self))[@sizeOf(Self) - 1] ^ 0b1000_0000;
        } else {
            return self.length;
        }
    }

    /// Return true if the string has zero length.
    pub fn isEmpty(self: Self) bool {
        return self.len() == 0;
    }

    /// Return true if this string is stored inline (small string optimization).
    pub fn isSmallStr(self: Self) bool {
        return @as(isize, @bitCast(self.length)) < 0;
    }

    /// Return true if this string is a seamless slice into another allocation.
    pub fn isSeamlessSlice(self: Self) bool {
        return !self.isSmallStr() and (self.capacity_or_alloc_ptr & seamless_slice_tag) != 0;
    }

    /// Return a pointer to the raw UTF-8 bytes.
    pub fn asU8ptr(self: *const Self) [*]const u8 {
        if (self.isSmallStr()) {
            return @as([*]const u8, @ptrCast(self));
        } else {
            return @as([*]const u8, @ptrCast(self.bytes));
        }
    }

    /// Return an empty RocStr.
    pub fn empty() Self {
        return .{ .bytes = null, .capacity_or_alloc_ptr = 0, .length = small_str_bit };
    }

    /// Create a RocStr from a byte slice, using `roc_ops` for heap allocation if needed.
    pub fn fromSlice(slice: []const u8, roc_ops: *RocOps) Self {
        if (slice.len < small_string_size) {
            var result = Self.empty();
            const ptr: [*]u8 = @ptrCast(&result);
            @memcpy(ptr[0..slice.len], slice);
            ptr[@sizeOf(Self) - 1] = @as(u8, @intCast(slice.len)) | 0b1000_0000;
            return result;
        } else {
            const ptr_width = @sizeOf(usize);
            const extra_bytes = ptr_width;
            const total = extra_bytes + slice.len;
            var alloc_args: RocAlloc = .{
                .alignment = @alignOf(usize),
                .length = total,
                .answer = undefined,
            };
            roc_ops.roc_alloc(&alloc_args, roc_ops.env);
            const base: [*]u8 = @ptrCast(alloc_args.answer);
            const data_ptr = base + extra_bytes;
            const rc: *isize = @ptrFromInt(@intFromPtr(data_ptr) - @sizeOf(isize));
            rc.* = 1;
            @memcpy(data_ptr[0..slice.len], slice.ptr[0..slice.len]);
            return .{
                .bytes = data_ptr,
                .capacity_or_alloc_ptr = slice.len << 1,
                .length = slice.len,
            };
        }
    }

    /// Decrement the reference count; frees the allocation when it reaches zero.
    pub fn decref(self: Self, roc_ops: *RocOps) void {
        if (self.isSmallStr()) return;
        const alloc_ptr = self.getAllocationPtr() orelse return;
        const data_addr = @intFromPtr(alloc_ptr);
        const rc: *isize = @ptrFromInt(data_addr - @sizeOf(isize));
        if (rc.* == 0) return; // REFCOUNT_STATIC_DATA — bytes are in read-only memory
        const prev = @atomicRmw(isize, rc, .Sub, 1, .monotonic);
        if (prev == 1) {
            const ptr_width = @sizeOf(usize);
            const base: *anyopaque = @ptrFromInt(data_addr - ptr_width);
            var dealloc_args: RocDealloc = .{ .alignment = @alignOf(usize), .ptr = base };
            roc_ops.roc_dealloc(&dealloc_args, roc_ops.env);
        }
    }

    /// Increment the reference count by `amount`.
    pub fn incref(self: Self, amount: isize) void {
        if (self.isSmallStr()) return;
        const alloc_ptr = self.getAllocationPtr() orelse return;
        const rc: *isize = @ptrFromInt(@intFromPtr(alloc_ptr) - @sizeOf(isize));
        if (rc.* == 0) return; // REFCOUNT_STATIC_DATA
        _ = @atomicRmw(isize, rc, .Add, amount, .monotonic);
    }

    /// Return true if this string has a reference count of exactly one.
    pub fn isUnique(self: Self) bool {
        if (self.isSmallStr()) return true;
        const alloc_ptr = self.getAllocationPtr() orelse return true;
        const rc: *const isize = @ptrFromInt(@intFromPtr(alloc_ptr) - @sizeOf(isize));
        if (rc.* == 0) return true; // REFCOUNT_STATIC_DATA — treated as unique
        return rc.* == 1;
    }

    fn getAllocationPtr(self: Self) ?[*]u8 {
        if (self.isSeamlessSlice()) {
            return @as(?[*]u8, @ptrFromInt(self.capacity_or_alloc_ptr & ~seamless_slice_tag));
        } else {
            return self.bytes;
        }
    }
};

/// A generic Roc list. Elements are reference-counted and heap-allocated.
///
/// When `elements_refcounted` is true (the default), an extra `ptr_width` bytes
/// are reserved in the allocation header for the element count, matching the Roc
/// runtime's `allocateWithRefcount` layout. Set to `false` for lists of
/// non-refcounted primitives (e.g. `U8`, `I32`).
pub fn RocList(comptime T: type) type {
    return RocListWith(T, true);
}

/// Parameterized list constructor; use `RocList(T)` for refcounted elements.
pub fn RocListWith(comptime T: type, comptime elements_refcounted: bool) type {
    return extern struct {
        elements_ptr: ?[*]T,
        length: usize,
        capacity_or_alloc_ptr: usize,

        const Self = @This();
        const ptr_width = @sizeOf(usize);
        const required_space: usize = if (elements_refcounted) (2 * ptr_width) else ptr_width;
        const header_bytes = @max(required_space, @alignOf(T));
        const alloc_align = @max(ptr_width, @alignOf(T));

        /// Return the list elements as a `[]const T` slice.
        pub fn items(self: Self) []const T {
            if (self.elements_ptr) |ptr| return ptr[0..self.length];
            return &[_]T{};
        }

        /// Return the number of elements in the list.
        pub fn len(self: Self) usize {
            return self.length;
        }

        /// Return true if the list has zero elements.
        pub fn isEmpty(self: Self) bool {
            return self.length == 0;
        }

        /// Return true if this list is a seamless slice into another allocation.
        /// Slices share the rc slot with their backing allocation; the alloc ptr is
        /// encoded in `capacity_or_alloc_ptr` with the low bit set.
        pub fn isSeamlessSlice(self: Self) bool {
            return (self.capacity_or_alloc_ptr & 1) != 0;
        }

        /// Return an empty RocList.
        pub fn empty() Self {
            return .{ .elements_ptr = null, .length = 0, .capacity_or_alloc_ptr = 0 };
        }

        /// Resolve `self` to the start of its backing allocation (the element block
        /// just after the rc slot). Returns `null` for empty lists. Handles both
        /// whole-backing and seamless-slice forms.
        fn getAllocationPtr(self: Self) ?[*]u8 {
            if (self.isSeamlessSlice()) {
                return @as(?[*]u8, @ptrFromInt(self.capacity_or_alloc_ptr & ~@as(usize, 1)));
            }
            const ptr = self.elements_ptr orelse return null;
            return @ptrCast(ptr);
        }

        /// Allocate a new list with space for `length` elements.
        pub fn allocate(length: usize, roc_ops: *RocOps) Self {
            if (length == 0) return empty();
            const data_bytes = length * @sizeOf(T);
            const total = data_bytes + header_bytes;
            var alloc_args: RocAlloc = .{
                .alignment = alloc_align,
                .length = total,
                .answer = undefined,
            };
            roc_ops.roc_alloc(&alloc_args, roc_ops.env);
            const base: [*]u8 = @ptrCast(alloc_args.answer);
            const data_ptr = base + header_bytes;
            const rc: *isize = @ptrFromInt(@intFromPtr(data_ptr) - @sizeOf(isize));
            rc.* = 1;
            return .{
                .elements_ptr = @ptrCast(@alignCast(data_ptr)),
                .length = length,
                .capacity_or_alloc_ptr = length << 1,
            };
        }

        /// Create a RocList from a slice, copying elements into a new allocation.
        pub fn fromSlice(slice: []const T, roc_ops: *RocOps) Self {
            if (slice.len == 0) return empty();
            const list = allocate(slice.len, roc_ops);
            const dest: [*]u8 = @ptrCast(list.elements_ptr.?);
            const src: [*]const u8 = @ptrCast(slice.ptr);
            @memcpy(dest[0 .. slice.len * @sizeOf(T)], src[0 .. slice.len * @sizeOf(T)]);
            return list;
        }

        /// Decrement the reference count; frees the allocation when it reaches zero.
        pub fn decref(self: Self, roc_ops: *RocOps) void {
            const alloc_ptr = self.getAllocationPtr() orelse return;
            const data_addr = @intFromPtr(alloc_ptr);
            const rc: *isize = @ptrFromInt(data_addr - @sizeOf(isize));
            if (rc.* == 0) return; // REFCOUNT_STATIC_DATA — bytes are in read-only memory
            const prev = @atomicRmw(isize, rc, .Sub, 1, .monotonic);
            if (prev == 1) {
                const base: *anyopaque = @ptrFromInt(data_addr - header_bytes);
                var dealloc_args: RocDealloc = .{
                    .alignment = alloc_align,
                    .ptr = base,
                };
                roc_ops.roc_dealloc(&dealloc_args, roc_ops.env);
            }
        }

        /// Increment the reference count by `amount`.
        pub fn incref(self: Self, amount: isize) void {
            const alloc_ptr = self.getAllocationPtr() orelse return;
            const rc: *isize = @ptrFromInt(@intFromPtr(alloc_ptr) - @sizeOf(isize));
            if (rc.* == 0) return; // REFCOUNT_STATIC_DATA
            _ = @atomicRmw(isize, rc, .Add, amount, .monotonic);
        }

        /// Return true if this list has a reference count of exactly one.
        pub fn isUnique(self: Self) bool {
            const alloc_ptr = self.getAllocationPtr() orelse return true;
            const rc: *const isize = @ptrFromInt(@intFromPtr(alloc_ptr) - @sizeOf(isize));
            if (rc.* == 0) return true; // REFCOUNT_STATIC_DATA — treated as unique
            return rc.* == 1;
        }
    };
}

/// Minimal I/O abstraction for Roc platform hosts.
///
/// Provides stderr output and fatal-error handling that can be routed
/// to different backends (POSIX, freestanding/WASM, custom).
///
/// Use `RocIo.default()` for most platforms; inject a custom vtable for
/// environments without POSIX stdio (e.g. WASM freestanding).
pub const RocIo = struct {
    ctx: ?*anyopaque,
    vtable: *const VTable,

    pub const VTable = struct {
        /// Write to stderr. Best-effort: errors are silently ignored.
        writeStderr: *const fn (?*anyopaque, []const u8) void,
        /// Terminate the process or trap. Must not return.
        onFatal: *const fn (?*anyopaque) noreturn,
    };

    /// Write `data` to stderr (best-effort).
    pub fn writeStderr(self: RocIo, data: []const u8) void {
        self.vtable.writeStderr(self.ctx, data);
    }

    /// Terminate the process or trap. Does not return.
    pub fn onFatal(self: RocIo) noreturn {
        self.vtable.onFatal(self.ctx);
    }

    /// Native (POSIX) implementation: writes to stderr, exits with code 1.
    pub fn native() RocIo {
        return .{ .ctx = null, .vtable = &native_vtable };
    }

    /// Freestanding implementation: no-op stderr, @trap() on fatal.
    pub fn freestanding() RocIo {
        return .{ .ctx = null, .vtable = &freestanding_vtable };
    }

    /// Select the appropriate implementation for the current build target.
    pub fn default() RocIo {
        if (comptime builtin.os.tag == .freestanding) {
            return freestanding();
        }
        return native();
    }

    fn nativeWriteStderr(_: ?*anyopaque, data: []const u8) void {
        std.fs.File.stderr().writeAll(data) catch {};
    }

    fn nativeOnFatal(_: ?*anyopaque) noreturn {
        std.process.exit(1);
    }

    fn freestandingWriteStderr(_: ?*anyopaque, _: []const u8) void {}

    fn freestandingOnFatal(_: ?*anyopaque) noreturn {
        @trap();
    }

    const native_vtable: VTable = .{
        .writeStderr = &nativeWriteStderr,
        .onFatal = &nativeOnFatal,
    };

    const freestanding_vtable: VTable = .{
        .writeStderr = &freestandingWriteStderr,
        .onFatal = &freestandingOnFatal,
    };
};

/// Host environment passed to the Roc runtime.
///
/// Bundles the allocator and I/O backend used by DefaultAllocators
/// and DefaultHandlers.
pub const RocEnv = struct {
    allocator: std.mem.Allocator,
    roc_io: RocIo,
};

/// Element type for __AnonStruct10
/// NOTE: ZigGlue emits `init!`/`update!` as field names here, which is invalid
/// Zig (`!` is not allowed in identifiers). Renamed to `init_fn`/`update_fn`
/// locally; nothing in our host references this struct. Upstream bug to fix in
/// ZigGlue's field-name sanitization.
pub const __AnonStruct10 = extern struct {
    init_fn: *anyopaque,
    update_fn: *anyopaque,
};

/// Arguments for Host.blit!
/// Roc signature: List(U8), I32, I32, U32, U32, U32 => {}
/// Refcounted fields are owned by the hosted function.
pub const HostBlitArgs = extern struct {
    arg0: RocListWith(u8, false),
    arg1: i32,
    arg2: i32,
    arg3: u32,
    arg4: u32,
    arg5: u32,
};

/// Arguments for Host.blit_sub!
/// Roc signature: List(U8), I32, I32, U32, U32, U32, U32, U32, U32 => {}
/// Refcounted fields are owned by the hosted function.
pub const HostBlit_subArgs = extern struct {
    arg0: RocListWith(u8, false),
    arg1: i32,
    arg2: i32,
    arg3: u32,
    arg4: u32,
    arg5: u32,
    arg6: u32,
    arg7: u32,
    arg8: u32,
};

/// Arguments for Host.disk_write!
/// Roc signature: List(U8) => Bool
/// Refcounted fields are owned by the hosted function.
pub const HostDisk_writeArgs = extern struct {
    arg0: RocListWith(u8, false),
};

/// Arguments for Host.get_gamepad!
/// Roc signature: U8 => U8
/// Refcounted fields are owned by the hosted function.
pub const HostGet_gamepadArgs = extern struct {
    arg0: u8,
};

/// Arguments for Host.get_palette_color!
/// Roc signature: U8 => U32
/// Refcounted fields are owned by the hosted function.
pub const HostGet_palette_colorArgs = extern struct {
    arg0: u8,
};

/// Arguments for Host.get_pixel!
/// Roc signature: U8, U8 => U8
/// Refcounted fields are owned by the hosted function.
pub const HostGet_pixelArgs = extern struct {
    arg0: u8,
    arg1: u8,
};

/// Arguments for Host.hline!
/// Roc signature: I32, I32, U32 => {}
/// Refcounted fields are owned by the hosted function.
pub const HostHlineArgs = extern struct {
    arg0: i32,
    arg1: i32,
    arg2: u32,
};

/// Arguments for Host.line!
/// Roc signature: I32, I32, I32, I32 => {}
/// Refcounted fields are owned by the hosted function.
pub const HostLineArgs = extern struct {
    arg0: i32,
    arg1: i32,
    arg2: i32,
    arg3: i32,
};

/// Arguments for Host.oval!
/// Roc signature: I32, I32, U32, U32 => {}
/// Refcounted fields are owned by the hosted function.
pub const HostOvalArgs = extern struct {
    arg0: i32,
    arg1: i32,
    arg2: u32,
    arg3: u32,
};

/// Arguments for Host.rand_range_less_than!
/// Roc signature: I32, I32 => I32
/// Refcounted fields are owned by the hosted function.
pub const HostRand_range_less_thanArgs = extern struct {
    arg0: i32,
    arg1: i32,
};

/// Arguments for Host.rect!
/// Roc signature: I32, I32, U32, U32 => {}
/// Refcounted fields are owned by the hosted function.
pub const HostRectArgs = extern struct {
    arg0: i32,
    arg1: i32,
    arg2: u32,
    arg3: u32,
};

/// Arguments for Host.seed_rand!
/// Roc signature: U64 => {}
/// Refcounted fields are owned by the hosted function.
pub const HostSeed_randArgs = extern struct {
    arg0: u64,
};

/// Arguments for Host.set_draw_colors!
/// Roc signature: U16 => {}
/// Refcounted fields are owned by the hosted function.
pub const HostSet_draw_colorsArgs = extern struct {
    arg0: u16,
};

/// Arguments for Host.set_hide_gamepad_overlay!
/// Roc signature: Bool => {}
/// Refcounted fields are owned by the hosted function.
pub const HostSet_hide_gamepad_overlayArgs = extern struct {
    arg0: bool,
};

/// Arguments for Host.set_palette!
/// Roc signature: U32, U32, U32, U32 => {}
/// Refcounted fields are owned by the hosted function.
pub const HostSet_paletteArgs = extern struct {
    arg0: u32,
    arg1: u32,
    arg2: u32,
    arg3: u32,
};

/// Arguments for Host.set_pixel!
/// Roc signature: U8, U8, U8 => {}
/// Refcounted fields are owned by the hosted function.
pub const HostSet_pixelArgs = extern struct {
    arg0: u8,
    arg1: u8,
    arg2: u8,
};

/// Arguments for Host.set_preserve_frame_buffer!
/// Roc signature: Bool => {}
/// Refcounted fields are owned by the hosted function.
pub const HostSet_preserve_frame_bufferArgs = extern struct {
    arg0: bool,
};

/// Arguments for Host.text!
/// Roc signature: Str, I32, I32 => {}
/// Refcounted fields are owned by the hosted function.
pub const HostTextArgs = extern struct {
    arg0: RocStr,
    arg1: i32,
    arg2: i32,
};

/// Arguments for Host.tone!
/// Roc signature: U32, U32, U16, U8 => {}
/// Refcounted fields are owned by the hosted function.
pub const HostToneArgs = extern struct {
    arg0: u32,
    arg1: u32,
    arg2: u16,
    arg3: u8,
};

/// Arguments for Host.trace!
/// Roc signature: Str => {}
/// Refcounted fields are owned by the hosted function.
pub const HostTraceArgs = extern struct {
    arg0: RocStr,
};

/// Arguments for Host.vline!
/// Roc signature: I32, I32, U32 => {}
/// Refcounted fields are owned by the hosted function.
pub const HostVlineArgs = extern struct {
    arg0: i32,
    arg1: i32,
    arg2: u32,
};

/// Implement this struct with your hosted function implementations.
/// Refcounted hosted arguments are owned by the hosted function.
/// Pass it to hostedFunctions() to create the dispatch table.
pub const PlatformHostedFns = struct {
    host_blit: *const fn (*RocOps, *anyopaque, *const HostBlitArgs) callconv(.c) void, // Host.blit!
    host_blit_sub: *const fn (*RocOps, *anyopaque, *const HostBlit_subArgs) callconv(.c) void, // Host.blit_sub!
    host_disk_read: *const fn (*RocOps, *RocListWith(u8, false), *anyopaque) callconv(.c) void, // Host.disk_read!
    host_disk_write: *const fn (*RocOps, *bool, *const HostDisk_writeArgs) callconv(.c) void, // Host.disk_write!
    host_get_draw_colors: *const fn (*RocOps, *u16, *anyopaque) callconv(.c) void, // Host.get_draw_colors!
    host_get_gamepad: *const fn (*RocOps, *u8, *const HostGet_gamepadArgs) callconv(.c) void, // Host.get_gamepad!
    host_get_mouse_buttons: *const fn (*RocOps, *u8, *anyopaque) callconv(.c) void, // Host.get_mouse_buttons!
    host_get_mouse_x: *const fn (*RocOps, *i16, *anyopaque) callconv(.c) void, // Host.get_mouse_x!
    host_get_mouse_y: *const fn (*RocOps, *i16, *anyopaque) callconv(.c) void, // Host.get_mouse_y!
    host_get_netplay: *const fn (*RocOps, *u8, *anyopaque) callconv(.c) void, // Host.get_netplay!
    host_get_palette_color: *const fn (*RocOps, *u32, *const HostGet_palette_colorArgs) callconv(.c) void, // Host.get_palette_color!
    host_get_pixel: *const fn (*RocOps, *u8, *const HostGet_pixelArgs) callconv(.c) void, // Host.get_pixel!
    host_hline: *const fn (*RocOps, *anyopaque, *const HostHlineArgs) callconv(.c) void, // Host.hline!
    host_line: *const fn (*RocOps, *anyopaque, *const HostLineArgs) callconv(.c) void, // Host.line!
    host_oval: *const fn (*RocOps, *anyopaque, *const HostOvalArgs) callconv(.c) void, // Host.oval!
    host_rand: *const fn (*RocOps, *i32, *anyopaque) callconv(.c) void, // Host.rand!
    host_rand_range_less_than: *const fn (*RocOps, *i32, *const HostRand_range_less_thanArgs) callconv(.c) void, // Host.rand_range_less_than!
    host_rect: *const fn (*RocOps, *anyopaque, *const HostRectArgs) callconv(.c) void, // Host.rect!
    host_seed_rand: *const fn (*RocOps, *anyopaque, *const HostSeed_randArgs) callconv(.c) void, // Host.seed_rand!
    host_set_draw_colors: *const fn (*RocOps, *anyopaque, *const HostSet_draw_colorsArgs) callconv(.c) void, // Host.set_draw_colors!
    host_set_hide_gamepad_overlay: *const fn (*RocOps, *anyopaque, *const HostSet_hide_gamepad_overlayArgs) callconv(.c) void, // Host.set_hide_gamepad_overlay!
    host_set_palette: *const fn (*RocOps, *anyopaque, *const HostSet_paletteArgs) callconv(.c) void, // Host.set_palette!
    host_set_pixel: *const fn (*RocOps, *anyopaque, *const HostSet_pixelArgs) callconv(.c) void, // Host.set_pixel!
    host_set_preserve_frame_buffer: *const fn (*RocOps, *anyopaque, *const HostSet_preserve_frame_bufferArgs) callconv(.c) void, // Host.set_preserve_frame_buffer!
    host_text: *const fn (*RocOps, *anyopaque, *const HostTextArgs) callconv(.c) void, // Host.text!
    host_tone: *const fn (*RocOps, *anyopaque, *const HostToneArgs) callconv(.c) void, // Host.tone!
    host_trace: *const fn (*RocOps, *anyopaque, *const HostTraceArgs) callconv(.c) void, // Host.trace!
    host_vline: *const fn (*RocOps, *anyopaque, *const HostVlineArgs) callconv(.c) void, // Host.vline!
};

/// Create a HostedFunctions dispatch table from your implementations.
/// The comptime parameter + nested struct ensures the function pointer array
/// lives in static memory, not on the stack.
pub fn hostedFunctions(comptime fns: PlatformHostedFns) HostedFunctions {
    const Static = struct {
        const ptrs = [_]HostedFn{
            hostedFn(fns.host_blit), // Host.blit! (index 0)
            hostedFn(fns.host_blit_sub), // Host.blit_sub! (index 1)
            hostedFn(fns.host_disk_read), // Host.disk_read! (index 2)
            hostedFn(fns.host_disk_write), // Host.disk_write! (index 3)
            hostedFn(fns.host_get_draw_colors), // Host.get_draw_colors! (index 4)
            hostedFn(fns.host_get_gamepad), // Host.get_gamepad! (index 5)
            hostedFn(fns.host_get_mouse_buttons), // Host.get_mouse_buttons! (index 6)
            hostedFn(fns.host_get_mouse_x), // Host.get_mouse_x! (index 7)
            hostedFn(fns.host_get_mouse_y), // Host.get_mouse_y! (index 8)
            hostedFn(fns.host_get_netplay), // Host.get_netplay! (index 9)
            hostedFn(fns.host_get_palette_color), // Host.get_palette_color! (index 10)
            hostedFn(fns.host_get_pixel), // Host.get_pixel! (index 11)
            hostedFn(fns.host_hline), // Host.hline! (index 12)
            hostedFn(fns.host_line), // Host.line! (index 13)
            hostedFn(fns.host_oval), // Host.oval! (index 14)
            hostedFn(fns.host_rand), // Host.rand! (index 15)
            hostedFn(fns.host_rand_range_less_than), // Host.rand_range_less_than! (index 16)
            hostedFn(fns.host_rect), // Host.rect! (index 17)
            hostedFn(fns.host_seed_rand), // Host.seed_rand! (index 18)
            hostedFn(fns.host_set_draw_colors), // Host.set_draw_colors! (index 19)
            hostedFn(fns.host_set_hide_gamepad_overlay), // Host.set_hide_gamepad_overlay! (index 20)
            hostedFn(fns.host_set_palette), // Host.set_palette! (index 21)
            hostedFn(fns.host_set_pixel), // Host.set_pixel! (index 22)
            hostedFn(fns.host_set_preserve_frame_buffer), // Host.set_preserve_frame_buffer! (index 23)
            hostedFn(fns.host_text), // Host.text! (index 24)
            hostedFn(fns.host_tone), // Host.tone! (index 25)
            hostedFn(fns.host_trace), // Host.trace! (index 26)
            hostedFn(fns.host_vline), // Host.vline! (index 27)
        };
    };
    return .{
        .count = Static.ptrs.len,
        .fns = @constCast(&Static.ptrs),
    };
}

/// Default memory management functions for Roc platforms.
///
/// Uses `RocEnv.allocator` for allocation. Each allocation prepends
/// size metadata so that dealloc/realloc can recover the original
/// allocation size (required because `roc_dealloc` receives no length).
pub const DefaultAllocators = struct {
    /// Allocate memory for the Roc runtime.
    pub fn rocAlloc(alloc_args: *RocAlloc, env_ptr: *anyopaque) callconv(.c) void {
        const env: *RocEnv = @ptrCast(@alignCast(env_ptr));
        const allocator = env.allocator;

        const min_alignment: usize = @max(alloc_args.alignment, @alignOf(usize));
        const align_enum = std.mem.Alignment.fromByteUnits(min_alignment);
        const size_storage_bytes = min_alignment;
        const total_size = alloc_args.length + size_storage_bytes;

        const base_ptr = allocator.rawAlloc(total_size, align_enum, @returnAddress()) orelse {
            env.roc_io.writeStderr("roc_alloc: out of memory\n");
            env.roc_io.onFatal();
        };

        // Store total size immediately before the user data pointer
        const size_ptr: *usize = @ptrFromInt(@intFromPtr(base_ptr) + size_storage_bytes - @sizeOf(usize));
        size_ptr.* = total_size;

        alloc_args.answer = @ptrFromInt(@intFromPtr(base_ptr) + size_storage_bytes);
    }

    /// Free memory previously allocated by `rocAlloc`.
    pub fn rocDealloc(dealloc_args: *RocDealloc, env_ptr: *anyopaque) callconv(.c) void {
        const env: *RocEnv = @ptrCast(@alignCast(env_ptr));
        const allocator = env.allocator;

        const min_alignment: usize = @max(dealloc_args.alignment, @alignOf(usize));
        const align_enum = std.mem.Alignment.fromByteUnits(min_alignment);
        const size_storage_bytes = min_alignment;

        const size_ptr: *const usize = @ptrFromInt(@intFromPtr(dealloc_args.ptr) - @sizeOf(usize));
        const total_size = size_ptr.*;

        const base_ptr: [*]u8 = @ptrFromInt(@intFromPtr(dealloc_args.ptr) - size_storage_bytes);
        const slice = base_ptr[0..total_size];
        allocator.rawFree(slice, align_enum, @returnAddress());
    }

    /// Reallocate memory, copying existing data to the new allocation.
    pub fn rocRealloc(realloc_args: *RocRealloc, env_ptr: *anyopaque) callconv(.c) void {
        const env: *RocEnv = @ptrCast(@alignCast(env_ptr));
        const allocator = env.allocator;

        const min_alignment: usize = @max(realloc_args.alignment, @alignOf(usize));
        const align_enum = std.mem.Alignment.fromByteUnits(min_alignment);
        const size_storage_bytes = min_alignment;

        // Read old size from metadata
        const old_size_ptr: *const usize = @ptrFromInt(@intFromPtr(realloc_args.answer) - @sizeOf(usize));
        const old_total_size = old_size_ptr.*;
        const old_base_ptr: [*]u8 = @ptrFromInt(@intFromPtr(realloc_args.answer) - size_storage_bytes);

        // Allocate new block
        const new_total_size = realloc_args.new_length + size_storage_bytes;
        const new_base_ptr = allocator.rawAlloc(new_total_size, align_enum, @returnAddress()) orelse {
            env.roc_io.writeStderr("roc_realloc: out of memory\n");
            env.roc_io.onFatal();
        };

        // Copy old user data to new location
        const old_user_data_size = old_total_size - size_storage_bytes;
        const copy_size = @min(old_user_data_size, realloc_args.new_length);
        const new_user_ptr: [*]u8 = @ptrFromInt(@intFromPtr(new_base_ptr) + size_storage_bytes);
        const old_user_ptr: [*]const u8 = @ptrCast(realloc_args.answer);
        @memcpy(new_user_ptr[0..copy_size], old_user_ptr[0..copy_size]);

        // Free old allocation
        allocator.rawFree(old_base_ptr[0..old_total_size], align_enum, @returnAddress());

        // Store new size and return user pointer
        const new_size_ptr: *usize = @ptrFromInt(@intFromPtr(new_base_ptr) + size_storage_bytes - @sizeOf(usize));
        new_size_ptr.* = new_total_size;
        realloc_args.answer = new_user_ptr;
    }
};

/// Default handlers for dbg, expect-failed, and crash.
///
/// Routes output through `RocEnv.roc_io` for platform portability.
pub const DefaultHandlers = struct {
    /// Print a `dbg` expression to stderr.
    pub fn rocDbg(dbg_args: *const RocDbg, env_ptr: *anyopaque) callconv(.c) void {
        const env: *RocEnv = @ptrCast(@alignCast(env_ptr));
        const msg = dbg_args.utf8_bytes[0..dbg_args.len];
        env.roc_io.writeStderr("[ROC DBG] ");
        env.roc_io.writeStderr(msg);
        env.roc_io.writeStderr("\n");
    }

    /// Print a failed `expect` to stderr.
    pub fn rocExpectFailed(expect_args: *const RocExpectFailed, env_ptr: *anyopaque) callconv(.c) void {
        const env: *RocEnv = @ptrCast(@alignCast(env_ptr));
        const msg = expect_args.utf8_bytes[0..expect_args.len];
        env.roc_io.writeStderr("[ROC EXPECT] ");
        env.roc_io.writeStderr(msg);
        env.roc_io.writeStderr("\n");
    }

    /// Print a `crash` message to stderr and terminate.
    pub fn rocCrashed(crash_args: *const RocCrashed, env_ptr: *anyopaque) callconv(.c) void {
        const env: *RocEnv = @ptrCast(@alignCast(env_ptr));
        const msg = crash_args.utf8_bytes[0..crash_args.len];
        env.roc_io.writeStderr("[ROC CRASHED] ");
        env.roc_io.writeStderr(msg);
        env.roc_io.writeStderr("\n");
        env.roc_io.onFatal();
    }
};

/// Create a RocOps struct with default memory management and error handlers.
///
/// Wires `DefaultAllocators`, `DefaultHandlers`, and the provided hosted
/// functions into a ready-to-use `RocOps`.
///
/// Example:
/// ```zig
/// var env = RocEnv{ .allocator = gpa.allocator(), .roc_io = RocIo.default() };
/// var roc_ops = makeRocOps(&env, hostedFunctions(.{ ... }));
/// ```
pub fn makeRocOps(env: *RocEnv, hosted_fns: HostedFunctions) RocOps {
    return .{
        .env = @ptrCast(env),
        .roc_alloc = &DefaultAllocators.rocAlloc,
        .roc_dealloc = &DefaultAllocators.rocDealloc,
        .roc_realloc = &DefaultAllocators.rocRealloc,
        .roc_dbg = &DefaultHandlers.rocDbg,
        .roc_expect_failed = &DefaultHandlers.rocExpectFailed,
        .roc_crashed = &DefaultHandlers.rocCrashed,
        .hosted_fns = hosted_fns,
    };
}

// =============================================================================
// Entrypoint Declarations
//
// Extern declarations for Roc entrypoints. Call these from your platform host
// to invoke Roc application functions.
// =============================================================================

/// Entrypoint: init_for_host!
pub extern fn roc__init_for_host(ops: *RocOps, ret_ptr: ***anyopaque, arg_ptr: ?*anyopaque) callconv(.c) void;

/// Entrypoint: update_for_host!
pub extern fn roc__update_for_host(ops: *RocOps, ret_ptr: ***anyopaque, arg_ptr: ?*const **anyopaque) callconv(.c) void;
