//! Roc Platform ABI
//!
//! This file defines Zig declarations for the direct symbol ABI used by a Roc platform.
//! It is automatically generated by the Roc glue generator.
//!
//! Hosted argument ownership:
//! - Roc transfers ownership of refcounted arguments to the hosted function.
//! - The hosted function must decref owned refcounted arguments when done.
//! - If the host stores or returns an argument, it must retain or transfer ownership explicitly.
//!
//! Import this file from the platform host and implement the listed hosted symbols
//! with the exact natural C ABI signatures shown below.

const std = @import("std");
const builtin = @import("builtin");

/// Runtime representation of an opaque `Box(T)` value.
pub const RocBox = ?*anyopaque;

/// Host-internal allocator and diagnostic context used by helper functions in this file.
///
/// Compiled Roc code does not receive this value. The real host ABI is the set of direct
/// linker symbols declared below (`roc_alloc`, hosted symbols, and provided entrypoints).
pub const RocHost = extern struct {
    env: *anyopaque,
    roc_alloc: *const fn (*RocHost, usize, usize) callconv(.c) ?*anyopaque,
    roc_dealloc: *const fn (*RocHost, *anyopaque, usize) callconv(.c) void,
    roc_realloc: *const fn (*RocHost, *anyopaque, usize, usize) callconv(.c) ?*anyopaque,
    roc_dbg: *const fn (*RocHost, [*]const u8, usize) callconv(.c) void,
    roc_expect_failed: *const fn (*RocHost, [*]const u8, usize) callconv(.c) void,
    roc_crashed: *const fn (*RocHost, [*]const u8, usize) callconv(.c) void,
};

/// Private erased-callable function pointer stored in `RocErasedCallablePayload`.
pub const RocErasedCallableFn = *const fn (*RocHost, ?[*]u8, ?[*]const u8, ?[*]u8) callconv(.c) void;

/// Final-drop callback for inline erased-callable captures.
pub const RocErasedCallableOnDrop = *const fn (?[*]u8, *RocHost) callconv(.c) void;

/// Payload header for `Box(function)`.
pub const RocErasedCallablePayload = extern struct {
    callable_fn_ptr: RocErasedCallableFn,
    on_drop: ?RocErasedCallableOnDrop,
};

/// Runtime representation of `Box(function)`.
pub const RocErasedCallable = ?[*]u8;

pub const roc_erased_callable_capture_alignment: usize = 16;
pub const roc_erased_callable_payload_alignment: usize = 16;
pub const roc_erased_callable_capture_offset: usize = std.mem.alignForward(usize, @sizeOf(RocErasedCallablePayload), roc_erased_callable_capture_alignment);

pub fn rocErasedCallablePayloadSize(capture_size: usize) usize {
    return roc_erased_callable_capture_offset + capture_size;
}

pub fn rocErasedCallablePayloadPtr(callable: RocErasedCallable) *RocErasedCallablePayload {
    return @ptrCast(@alignCast(callable orelse unreachable));
}

pub fn rocErasedCallableCapturePtr(callable: RocErasedCallable) ?[*]u8 {
    const data = callable orelse return null;
    return data + roc_erased_callable_capture_offset;
}

pub fn rocErasedCallableAllocate(
    roc_host: *RocHost,
    callable_fn_ptr: RocErasedCallableFn,
    on_drop: ?RocErasedCallableOnDrop,
    capture_size: usize,
) RocErasedCallable {
    const ptr_width = @sizeOf(usize);
    const alignment = @max(ptr_width, roc_erased_callable_payload_alignment);
    const extra_bytes = @max(ptr_width, roc_erased_callable_payload_alignment);
    const length = extra_bytes + rocErasedCallablePayloadSize(capture_size);
    const base: [*]u8 = @ptrCast(roc_host.roc_alloc(roc_host, length, alignment));
    const data = base + extra_bytes;
    const rc: *isize = @ptrFromInt(@intFromPtr(data) - @sizeOf(isize));
    rc.* = 1;
    const payload: *RocErasedCallablePayload = @ptrCast(@alignCast(data));
    payload.* = .{ .callable_fn_ptr = callable_fn_ptr, .on_drop = on_drop };
    return data;
}

/// Payload drop callback for a boxed value.
///
/// The callback receives the boxed payload data pointer and must recursively
/// decref any Roc refcounted values inside the payload. It must not free the
/// box allocation; `decrefBoxWith` and `freeBoxWith` free it after the callback.
pub const RocBoxPayloadDecref = *const fn (?*anyopaque, *RocHost) callconv(.c) void;

/// Increment the refcount of a boxed payload data pointer.
pub fn increfBox(data_ptr: ?*anyopaque, amount: isize) void {
    const data = boxDataPtr(data_ptr) orelse return;
    const rc = boxRefcountPtr(data);
    if (rc.* == 0) return; // REFCOUNT_STATIC_DATA
    _ = @atomicRmw(isize, rc, .Add, amount, .monotonic);
}

/// Decrement a pointer-aligned boxed payload with no Roc refcounted values.
pub fn decrefBox(data_ptr: ?*anyopaque, roc_host: *RocHost) void {
    decrefBoxWith(data_ptr, @alignOf(usize), null, roc_host);
}

/// Decrement a boxed payload and run payload teardown when this is the final ref.
pub fn decrefBoxWith(
    data_ptr: ?*anyopaque,
    payload_alignment: usize,
    payload_decref: ?RocBoxPayloadDecref,
    roc_host: *RocHost,
) void {
    const data = boxDataPtr(data_ptr) orelse return;
    const rc = boxRefcountPtr(data);
    if (rc.* == 0) return; // REFCOUNT_STATIC_DATA

    const prev = @atomicRmw(isize, rc, .Sub, 1, .monotonic);
    if (prev == 1) {
        if (payload_decref) |callback| callback(data_ptr, roc_host);
        freeBoxAllocation(data, payload_alignment, payload_decref != null, roc_host);
    }
}

/// Free a boxed payload allocation immediately after running payload teardown.
pub fn freeBoxWith(
    data_ptr: ?*anyopaque,
    payload_alignment: usize,
    payload_decref: ?RocBoxPayloadDecref,
    roc_host: *RocHost,
) void {
    const data = boxDataPtr(data_ptr) orelse return;
    if (payload_decref) |callback| callback(data_ptr, roc_host);
    freeBoxAllocation(data, payload_alignment, payload_decref != null, roc_host);
}

/// Return true when a boxed payload data pointer has exactly one live ref.
pub fn isUniqueBox(data_ptr: ?*anyopaque) bool {
    const data = boxDataPtr(data_ptr) orelse return true;
    const rc = boxRefcountPtr(data);
    return rc.* == 1;
}

fn boxDataPtr(data_ptr: ?*anyopaque) ?[*]u8 {
    const ptr = data_ptr orelse return null;
    return @ptrCast(ptr);
}

fn boxRefcountPtr(data: [*]u8) *isize {
    return @ptrFromInt(@intFromPtr(data) - @sizeOf(isize));
}

fn freeBoxAllocation(
    data: [*]u8,
    payload_alignment: usize,
    payload_contains_refcounted: bool,
    roc_host: *RocHost,
) void {
    const ptr_width = @sizeOf(usize);
    const required_space: usize = if (payload_contains_refcounted) (2 * ptr_width) else ptr_width;
    const header_bytes = @max(required_space, payload_alignment);
    const alloc_alignment = @max(ptr_width, payload_alignment);
    const base: *anyopaque = @ptrFromInt(@intFromPtr(data) - header_bytes);
    roc_host.roc_dealloc(roc_host, base, alloc_alignment);
}

/// A Roc string value. Small strings (up to 23 bytes) are stored inline;
/// larger strings are heap-allocated with a reference count.
///
/// `bytes` is never tagged. Operations, host code, glue code, and object-file
/// relocations can use it directly as the UTF-8 byte pointer for non-small
/// strings. Seamless-slice tagging lives in `capacity_or_alloc_ptr` instead.
/// Big-string capacity is stored shifted left by one bit, so max capacity is
/// essentially `std.math.maxInt(isize)` bytes: about 2 GiB on 32-bit targets
/// and 8 EiB on 64-bit targets.
pub const RocStr = extern struct {
    bytes: ?[*]u8,
    capacity_or_alloc_ptr: usize,
    length: usize,

    const Self = @This();
    const small_string_size = @sizeOf(RocStr);
    const small_str_max_length = small_string_size - 1;
    const small_str_bit: usize = @as(usize, @bitCast(@as(isize, std.math.minInt(isize))));
    const seamless_slice_tag: usize = 1;

    /// Return the string contents as a `[]const u8` slice.
    pub fn asSlice(self: *const Self) []const u8 {
        return self.asU8ptr()[0..self.len()];
    }

    /// Return the length of the string in bytes.
    pub fn len(self: Self) usize {
        if (self.isSmallStr()) {
            return @as([*]const u8, @ptrCast(&self))[@sizeOf(Self) - 1] ^ 0b1000_0000;
        } else {
            return self.length;
        }
    }

    /// Return true if the string has zero length.
    pub fn isEmpty(self: Self) bool {
        return self.len() == 0;
    }

    /// Return true if this string is stored inline (small string optimization).
    pub fn isSmallStr(self: Self) bool {
        return @as(isize, @bitCast(self.length)) < 0;
    }

    /// Return true if this string is a seamless slice into another allocation.
    pub fn isSeamlessSlice(self: Self) bool {
        return !self.isSmallStr() and (self.capacity_or_alloc_ptr & seamless_slice_tag) != 0;
    }

    /// Return a pointer to the raw UTF-8 bytes.
    pub fn asU8ptr(self: *const Self) [*]const u8 {
        if (self.isSmallStr()) {
            return @as([*]const u8, @ptrCast(self));
        } else {
            return @as([*]const u8, @ptrCast(self.bytes));
        }
    }

    /// Return an empty RocStr.
    pub fn empty() Self {
        return .{ .bytes = null, .capacity_or_alloc_ptr = 0, .length = small_str_bit };
    }

    /// Create a RocStr from a byte slice, using `roc_host` for heap allocation if needed.
    pub fn fromSlice(slice: []const u8, roc_host: *RocHost) Self {
        if (slice.len < small_string_size) {
            var result = Self.empty();
            const ptr: [*]u8 = @ptrCast(&result);
            @memcpy(ptr[0..slice.len], slice);
            ptr[@sizeOf(Self) - 1] = @as(u8, @intCast(slice.len)) | 0b1000_0000;
            return result;
        } else {
            const ptr_width = @sizeOf(usize);
            const extra_bytes = ptr_width;
            const total = extra_bytes + slice.len;
            const base: [*]u8 = @ptrCast(roc_host.roc_alloc(roc_host, total, @alignOf(usize)));
            const data_ptr = base + extra_bytes;
            const rc: *isize = @ptrFromInt(@intFromPtr(data_ptr) - @sizeOf(isize));
            rc.* = 1;
            @memcpy(data_ptr[0..slice.len], slice.ptr[0..slice.len]);
            return .{
                .bytes = data_ptr,
                .capacity_or_alloc_ptr = slice.len << 1,
                .length = slice.len,
            };
        }
    }

    /// Decrement the reference count; frees the allocation when it reaches zero.
    pub fn decref(self: Self, roc_host: *RocHost) void {
        if (self.isSmallStr()) return;
        const alloc_ptr = self.getAllocationPtr() orelse return;
        const data_addr = @intFromPtr(alloc_ptr);
        const rc: *isize = @ptrFromInt(data_addr - @sizeOf(isize));
        if (rc.* == 0) return; // REFCOUNT_STATIC_DATA — bytes are in read-only memory
        const prev = @atomicRmw(isize, rc, .Sub, 1, .monotonic);
        if (prev == 1) {
            const ptr_width = @sizeOf(usize);
            const base: *anyopaque = @ptrFromInt(data_addr - ptr_width);
            roc_host.roc_dealloc(roc_host, base, @alignOf(usize));
        }
    }

    /// Increment the reference count by `amount`.
    pub fn incref(self: Self, amount: isize) void {
        if (self.isSmallStr()) return;
        const alloc_ptr = self.getAllocationPtr() orelse return;
        const rc: *isize = @ptrFromInt(@intFromPtr(alloc_ptr) - @sizeOf(isize));
        if (rc.* == 0) return; // REFCOUNT_STATIC_DATA
        _ = @atomicRmw(isize, rc, .Add, amount, .monotonic);
    }

    /// Return true if this string has a reference count of exactly one.
    pub fn isUnique(self: Self) bool {
        if (self.isSmallStr()) return true;
        const alloc_ptr = self.getAllocationPtr() orelse return true;
        const rc: *const isize = @ptrFromInt(@intFromPtr(alloc_ptr) - @sizeOf(isize));
        if (rc.* == 0) return true; // REFCOUNT_STATIC_DATA — treated as unique
        return rc.* == 1;
    }

    fn getAllocationPtr(self: Self) ?[*]u8 {
        if (self.isSeamlessSlice()) {
            return @as(?[*]u8, @ptrFromInt(self.capacity_or_alloc_ptr & ~seamless_slice_tag));
        } else {
            return self.bytes;
        }
    }
};

/// A generic Roc list. Elements are reference-counted and heap-allocated.
///
/// When `elements_refcounted` is true (the default), an extra `ptr_width` bytes
/// are reserved in the allocation header for the element count, matching the Roc
/// runtime's `allocateWithRefcount` layout. Set to `false` for lists of
/// non-refcounted primitives (e.g. `U8`, `I32`).
pub fn RocList(comptime T: type) type {
    return RocListWith(T, true);
}

/// Parameterized list constructor; use `RocList(T)` for refcounted elements.
pub fn RocListWith(comptime T: type, comptime elements_refcounted: bool) type {
    return extern struct {
        elements_ptr: ?[*]T,
        length: usize,
        capacity_or_alloc_ptr: usize,

        const Self = @This();
        const ptr_width = @sizeOf(usize);
        const required_space: usize = if (elements_refcounted) (2 * ptr_width) else ptr_width;
        const header_bytes = @max(required_space, @alignOf(T));
        const alloc_align = @max(ptr_width, @alignOf(T));

        /// Return the list elements as a `[]const T` slice.
        pub fn items(self: Self) []const T {
            if (self.elements_ptr) |ptr| return ptr[0..self.length];
            return &[_]T{};
        }

        /// Return the number of elements in the list.
        pub fn len(self: Self) usize {
            return self.length;
        }

        /// Return true if the list has zero elements.
        pub fn isEmpty(self: Self) bool {
            return self.length == 0;
        }

        /// Return true if this list is a seamless slice into another allocation.
        /// Slices share the rc slot with their backing allocation; the alloc ptr is
        /// encoded in `capacity_or_alloc_ptr` with the low bit set.
        pub fn isSeamlessSlice(self: Self) bool {
            return (self.capacity_or_alloc_ptr & 1) != 0;
        }

        /// Return an empty RocList.
        pub fn empty() Self {
            return .{ .elements_ptr = null, .length = 0, .capacity_or_alloc_ptr = 0 };
        }

        /// Resolve `self` to the start of its backing allocation (the element block
        /// just after the rc slot). Returns `null` for empty lists. Handles both
        /// whole-backing and seamless-slice forms.
        fn getAllocationPtr(self: Self) ?[*]u8 {
            if (self.isSeamlessSlice()) {
                return @as(?[*]u8, @ptrFromInt(self.capacity_or_alloc_ptr & ~@as(usize, 1)));
            }
            const ptr = self.elements_ptr orelse return null;
            return @ptrCast(ptr);
        }

        /// Allocate a new list with space for `length` elements.
        pub fn allocate(length: usize, roc_host: *RocHost) Self {
            if (length == 0) return empty();
            const data_bytes = length * @sizeOf(T);
            const total = data_bytes + header_bytes;
            const base: [*]u8 = @ptrCast(roc_host.roc_alloc(roc_host, total, alloc_align));
            const data_ptr = base + header_bytes;
            const rc: *isize = @ptrFromInt(@intFromPtr(data_ptr) - @sizeOf(isize));
            rc.* = 1;
            return .{
                .elements_ptr = @ptrCast(@alignCast(data_ptr)),
                .length = length,
                .capacity_or_alloc_ptr = length << 1,
            };
        }

        /// Create a RocList from a slice, copying elements into a new allocation.
        pub fn fromSlice(slice: []const T, roc_host: *RocHost) Self {
            if (slice.len == 0) return empty();
            const list = allocate(slice.len, roc_host);
            const dest: [*]u8 = @ptrCast(list.elements_ptr.?);
            const src: [*]const u8 = @ptrCast(slice.ptr);
            @memcpy(dest[0 .. slice.len * @sizeOf(T)], src[0 .. slice.len * @sizeOf(T)]);
            return list;
        }

        /// Decrement the reference count; frees the allocation when it reaches zero.
        pub fn decref(self: Self, roc_host: *RocHost) void {
            const alloc_ptr = self.getAllocationPtr() orelse return;
            const data_addr = @intFromPtr(alloc_ptr);
            const rc: *isize = @ptrFromInt(data_addr - @sizeOf(isize));
            if (rc.* == 0) return; // REFCOUNT_STATIC_DATA — bytes are in read-only memory
            const prev = @atomicRmw(isize, rc, .Sub, 1, .monotonic);
            if (prev == 1) {
                const base: *anyopaque = @ptrFromInt(data_addr - header_bytes);
                roc_host.roc_dealloc(roc_host, base, alloc_align);
            }
        }

        /// Increment the reference count by `amount`.
        pub fn incref(self: Self, amount: isize) void {
            const alloc_ptr = self.getAllocationPtr() orelse return;
            const rc: *isize = @ptrFromInt(@intFromPtr(alloc_ptr) - @sizeOf(isize));
            if (rc.* == 0) return; // REFCOUNT_STATIC_DATA
            _ = @atomicRmw(isize, rc, .Add, amount, .monotonic);
        }

        /// Return true if this list has a reference count of exactly one.
        pub fn isUnique(self: Self) bool {
            const alloc_ptr = self.getAllocationPtr() orelse return true;
            const rc: *const isize = @ptrFromInt(@intFromPtr(alloc_ptr) - @sizeOf(isize));
            if (rc.* == 0) return true; // REFCOUNT_STATIC_DATA — treated as unique
            return rc.* == 1;
        }
    };
}

/// Minimal I/O abstraction for Roc platform hosts.
///
/// Provides stderr output and fatal-error handling that can be routed
/// to different backends (POSIX, freestanding/WASM, custom).
///
/// Use `RocIo.default()` for most platforms; inject a custom vtable for
/// environments without POSIX stdio (e.g. WASM freestanding).
pub const RocIo = struct {
    ctx: ?*anyopaque,
    vtable: *const VTable,

    pub const VTable = struct {
        /// Write to stderr. Best-effort: errors are silently ignored.
        writeStderr: *const fn (?*anyopaque, []const u8) void,
        /// Terminate the process or trap. Must not return.
        onFatal: *const fn (?*anyopaque) noreturn,
    };

    /// Write `data` to stderr (best-effort).
    pub fn writeStderr(self: RocIo, data: []const u8) void {
        self.vtable.writeStderr(self.ctx, data);
    }

    /// Terminate the process or trap. Does not return.
    pub fn onFatal(self: RocIo) noreturn {
        self.vtable.onFatal(self.ctx);
    }

    /// Native (POSIX) implementation: writes to stderr, exits with code 1.
    pub fn native() RocIo {
        return .{ .ctx = null, .vtable = &native_vtable };
    }

    /// Freestanding implementation: no-op stderr, @trap() on fatal.
    pub fn freestanding() RocIo {
        return .{ .ctx = null, .vtable = &freestanding_vtable };
    }

    /// Select the appropriate implementation for the current build target.
    pub fn default() RocIo {
        if (comptime builtin.os.tag == .freestanding) {
            return freestanding();
        }
        return native();
    }

    fn nativeWriteStderr(_: ?*anyopaque, data: []const u8) void {
        std.fs.File.stderr().writeAll(data) catch {};
    }

    fn nativeOnFatal(_: ?*anyopaque) noreturn {
        std.process.exit(1);
    }

    fn freestandingWriteStderr(_: ?*anyopaque, _: []const u8) void {}

    fn freestandingOnFatal(_: ?*anyopaque) noreturn {
        @trap();
    }

    const native_vtable: VTable = .{
        .writeStderr = &nativeWriteStderr,
        .onFatal = &nativeOnFatal,
    };

    const freestanding_vtable: VTable = .{
        .writeStderr = &freestandingWriteStderr,
        .onFatal = &freestandingOnFatal,
    };
};

/// Host environment passed to the Roc runtime.
///
/// Bundles the allocator and I/O backend used by DefaultAllocators
/// and DefaultHandlers.
pub const RocEnv = struct {
    allocator: std.mem.Allocator,
    roc_io: RocIo,
};

/// Element type for __AnonStruct10
pub const __AnonStruct10 = extern struct {
    @"init!": *anyopaque,
    @"update!": *anyopaque,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct10) != 16) @compileError("__AnonStruct10 size mismatch");
        if (@alignOf(__AnonStruct10) != 8) @compileError("__AnonStruct10 alignment mismatch");
    }
}

/// Arguments for Host.blit!
/// Roc signature: List(U8), I32, I32, U32, U32, U32 => {}
/// Refcounted fields are owned by the hosted function.
pub const HostBlitArgs = extern struct {
    arg0: RocListWith(u8, false),
    arg1: i32,
    arg2: i32,
    arg3: u32,
    arg4: u32,
    arg5: u32,
};

/// Arguments for Host.blit_sub!
/// Roc signature: List(U8), I32, I32, U32, U32, U32, U32, U32, U32 => {}
/// Refcounted fields are owned by the hosted function.
pub const HostBlit_subArgs = extern struct {
    arg0: RocListWith(u8, false),
    arg1: i32,
    arg2: i32,
    arg3: u32,
    arg4: u32,
    arg5: u32,
    arg6: u32,
    arg7: u32,
    arg8: u32,
};

/// Arguments for Host.disk_write!
/// Roc signature: List(U8) => Bool
/// Refcounted fields are owned by the hosted function.
pub const HostDisk_writeArgs = extern struct {
    arg0: RocListWith(u8, false),
};

/// Arguments for Host.get_gamepad!
/// Roc signature: U8 => U8
/// Refcounted fields are owned by the hosted function.
pub const HostGet_gamepadArgs = extern struct {
    arg0: u8,
};

/// Arguments for Host.get_palette_color!
/// Roc signature: U8 => U32
/// Refcounted fields are owned by the hosted function.
pub const HostGet_palette_colorArgs = extern struct {
    arg0: u8,
};

/// Arguments for Host.get_pixel!
/// Roc signature: U8, U8 => U8
/// Refcounted fields are owned by the hosted function.
pub const HostGet_pixelArgs = extern struct {
    arg0: u8,
    arg1: u8,
};

/// Arguments for Host.hline!
/// Roc signature: I32, I32, U32 => {}
/// Refcounted fields are owned by the hosted function.
pub const HostHlineArgs = extern struct {
    arg0: i32,
    arg1: i32,
    arg2: u32,
};

/// Arguments for Host.line!
/// Roc signature: I32, I32, I32, I32 => {}
/// Refcounted fields are owned by the hosted function.
pub const HostLineArgs = extern struct {
    arg0: i32,
    arg1: i32,
    arg2: i32,
    arg3: i32,
};

/// Arguments for Host.oval!
/// Roc signature: I32, I32, U32, U32 => {}
/// Refcounted fields are owned by the hosted function.
pub const HostOvalArgs = extern struct {
    arg0: i32,
    arg1: i32,
    arg2: u32,
    arg3: u32,
};

/// Arguments for Host.rand_range_less_than!
/// Roc signature: I32, I32 => I32
/// Refcounted fields are owned by the hosted function.
pub const HostRand_range_less_thanArgs = extern struct {
    arg0: i32,
    arg1: i32,
};

/// Arguments for Host.rect!
/// Roc signature: I32, I32, U32, U32 => {}
/// Refcounted fields are owned by the hosted function.
pub const HostRectArgs = extern struct {
    arg0: i32,
    arg1: i32,
    arg2: u32,
    arg3: u32,
};

/// Arguments for Host.seed_rand!
/// Roc signature: U64 => {}
/// Refcounted fields are owned by the hosted function.
pub const HostSeed_randArgs = extern struct {
    arg0: u64,
};

/// Arguments for Host.set_draw_colors!
/// Roc signature: U16 => {}
/// Refcounted fields are owned by the hosted function.
pub const HostSet_draw_colorsArgs = extern struct {
    arg0: u16,
};

/// Arguments for Host.set_hide_gamepad_overlay!
/// Roc signature: Bool => {}
/// Refcounted fields are owned by the hosted function.
pub const HostSet_hide_gamepad_overlayArgs = extern struct {
    arg0: bool,
};

/// Arguments for Host.set_palette!
/// Roc signature: U32, U32, U32, U32 => {}
/// Refcounted fields are owned by the hosted function.
pub const HostSet_paletteArgs = extern struct {
    arg0: u32,
    arg1: u32,
    arg2: u32,
    arg3: u32,
};

/// Arguments for Host.set_pixel!
/// Roc signature: U8, U8, U8 => {}
/// Refcounted fields are owned by the hosted function.
pub const HostSet_pixelArgs = extern struct {
    arg0: u8,
    arg1: u8,
    arg2: u8,
};

/// Arguments for Host.set_preserve_frame_buffer!
/// Roc signature: Bool => {}
/// Refcounted fields are owned by the hosted function.
pub const HostSet_preserve_frame_bufferArgs = extern struct {
    arg0: bool,
};

/// Arguments for Host.text!
/// Roc signature: Str, I32, I32 => {}
/// Refcounted fields are owned by the hosted function.
pub const HostTextArgs = extern struct {
    arg0: RocStr,
    arg1: i32,
    arg2: i32,
};

/// Arguments for Host.tone!
/// Roc signature: U32, U32, U16, U8 => {}
/// Refcounted fields are owned by the hosted function.
pub const HostToneArgs = extern struct {
    arg0: u32,
    arg1: u32,
    arg2: u16,
    arg3: u8,
};

/// Arguments for Host.trace!
/// Roc signature: Str => {}
/// Refcounted fields are owned by the hosted function.
pub const HostTraceArgs = extern struct {
    arg0: RocStr,
};

/// Arguments for Host.vline!
/// Roc signature: I32, I32, U32 => {}
/// Refcounted fields are owned by the hosted function.
pub const HostVlineArgs = extern struct {
    arg0: i32,
    arg1: i32,
    arg2: u32,
};


// =============================================================================
// Runtime Symbols
//
// The host defines these linker symbols. Compiled Roc code calls them directly.
// =============================================================================

pub extern fn roc_alloc(length: usize, alignment: usize) callconv(.c) ?*anyopaque;
pub extern fn roc_dealloc(ptr: *anyopaque, alignment: usize) callconv(.c) void;
pub extern fn roc_realloc(ptr: *anyopaque, new_length: usize, alignment: usize) callconv(.c) ?*anyopaque;
pub extern fn roc_dbg(bytes: [*]const u8, len: usize) callconv(.c) void;
pub extern fn roc_expect_failed(bytes: [*]const u8, len: usize) callconv(.c) void;
pub extern fn roc_crashed(bytes: [*]const u8, len: usize) callconv(.c) void;

// =============================================================================
// Hosted Symbols
//
// The platform host must export these symbols with the exact direct C ABI signatures.
// Refcounted arguments are owned by the hosted function.
// =============================================================================

/// Hosted symbol for Host.blit!
/// Roc signature: List(U8), I32, I32, U32, U32, U32 => {}
pub extern fn host_blit(arg0: RocListWith(u8, false), arg1: i32, arg2: i32, arg3: u32, arg4: u32, arg5: u32) callconv(.c) void;

/// Hosted symbol for Host.blit_sub!
/// Roc signature: List(U8), I32, I32, U32, U32, U32, U32, U32, U32 => {}
pub extern fn host_blit_sub(arg0: RocListWith(u8, false), arg1: i32, arg2: i32, arg3: u32, arg4: u32, arg5: u32, arg6: u32, arg7: u32, arg8: u32) callconv(.c) void;

/// Hosted symbol for Host.disk_read!
/// Roc signature: {} => List(U8)
pub extern fn host_disk_read() callconv(.c) RocListWith(u8, false);

/// Hosted symbol for Host.disk_write!
/// Roc signature: List(U8) => Bool
pub extern fn host_disk_write(arg0: RocListWith(u8, false)) callconv(.c) bool;

/// Hosted symbol for Host.get_draw_colors!
/// Roc signature: {} => U16
pub extern fn host_get_draw_colors() callconv(.c) u16;

/// Hosted symbol for Host.get_gamepad!
/// Roc signature: U8 => U8
pub extern fn host_get_gamepad(arg0: u8) callconv(.c) u8;

/// Hosted symbol for Host.get_mouse_buttons!
/// Roc signature: {} => U8
pub extern fn host_get_mouse_buttons() callconv(.c) u8;

/// Hosted symbol for Host.get_mouse_x!
/// Roc signature: {} => I16
pub extern fn host_get_mouse_x() callconv(.c) i16;

/// Hosted symbol for Host.get_mouse_y!
/// Roc signature: {} => I16
pub extern fn host_get_mouse_y() callconv(.c) i16;

/// Hosted symbol for Host.get_netplay!
/// Roc signature: {} => U8
pub extern fn host_get_netplay() callconv(.c) u8;

/// Hosted symbol for Host.get_palette_color!
/// Roc signature: U8 => U32
pub extern fn host_get_palette_color(arg0: u8) callconv(.c) u32;

/// Hosted symbol for Host.get_pixel!
/// Roc signature: U8, U8 => U8
pub extern fn host_get_pixel(arg0: u8, arg1: u8) callconv(.c) u8;

/// Hosted symbol for Host.hline!
/// Roc signature: I32, I32, U32 => {}
pub extern fn host_hline(arg0: i32, arg1: i32, arg2: u32) callconv(.c) void;

/// Hosted symbol for Host.line!
/// Roc signature: I32, I32, I32, I32 => {}
pub extern fn host_line(arg0: i32, arg1: i32, arg2: i32, arg3: i32) callconv(.c) void;

/// Hosted symbol for Host.oval!
/// Roc signature: I32, I32, U32, U32 => {}
pub extern fn host_oval(arg0: i32, arg1: i32, arg2: u32, arg3: u32) callconv(.c) void;

/// Hosted symbol for Host.rand!
/// Roc signature: {} => I32
pub extern fn host_rand() callconv(.c) i32;

/// Hosted symbol for Host.rand_range_less_than!
/// Roc signature: I32, I32 => I32
pub extern fn host_rand_range_less_than(arg0: i32, arg1: i32) callconv(.c) i32;

/// Hosted symbol for Host.rect!
/// Roc signature: I32, I32, U32, U32 => {}
pub extern fn host_rect(arg0: i32, arg1: i32, arg2: u32, arg3: u32) callconv(.c) void;

/// Hosted symbol for Host.seed_rand!
/// Roc signature: U64 => {}
pub extern fn host_seed_rand(arg0: u64) callconv(.c) void;

/// Hosted symbol for Host.set_draw_colors!
/// Roc signature: U16 => {}
pub extern fn host_set_draw_colors(arg0: u16) callconv(.c) void;

/// Hosted symbol for Host.set_hide_gamepad_overlay!
/// Roc signature: Bool => {}
pub extern fn host_set_hide_gamepad_overlay(arg0: bool) callconv(.c) void;

/// Hosted symbol for Host.set_palette!
/// Roc signature: U32, U32, U32, U32 => {}
pub extern fn host_set_palette(arg0: u32, arg1: u32, arg2: u32, arg3: u32) callconv(.c) void;

/// Hosted symbol for Host.set_pixel!
/// Roc signature: U8, U8, U8 => {}
pub extern fn host_set_pixel(arg0: u8, arg1: u8, arg2: u8) callconv(.c) void;

/// Hosted symbol for Host.set_preserve_frame_buffer!
/// Roc signature: Bool => {}
pub extern fn host_set_preserve_frame_buffer(arg0: bool) callconv(.c) void;

/// Hosted symbol for Host.text!
/// Roc signature: Str, I32, I32 => {}
pub extern fn host_text(arg0: RocStr, arg1: i32, arg2: i32) callconv(.c) void;

/// Hosted symbol for Host.tone!
/// Roc signature: U32, U32, U16, U8 => {}
pub extern fn host_tone(arg0: u32, arg1: u32, arg2: u16, arg3: u8) callconv(.c) void;

/// Hosted symbol for Host.trace!
/// Roc signature: Str => {}
pub extern fn host_trace(arg0: RocStr) callconv(.c) void;

/// Hosted symbol for Host.vline!
/// Roc signature: I32, I32, U32 => {}
pub extern fn host_vline(arg0: i32, arg1: i32, arg2: u32) callconv(.c) void;


/// Default memory management functions for Roc platforms.
///
/// Uses `RocEnv.allocator` for allocation. Each allocation prepends
/// size metadata so that dealloc/realloc can recover the original
/// allocation size (required because `roc_dealloc` receives no length).
pub const DefaultAllocators = struct {
    /// Allocate memory for the Roc runtime.
    pub fn rocAlloc(roc_host: *RocHost, length: usize, alignment: usize) callconv(.c) ?*anyopaque {
        const env: *RocEnv = @ptrCast(@alignCast(roc_host.env));
        const allocator = env.allocator;

        const min_alignment: usize = @max(alignment, @alignOf(usize));
        const align_enum = std.mem.Alignment.fromByteUnits(min_alignment);
        const size_storage_bytes = min_alignment;
        const total_size = length + size_storage_bytes;

        const base_ptr = allocator.rawAlloc(total_size, align_enum, @returnAddress()) orelse {
            env.roc_io.writeStderr("roc_alloc: out of memory\n");
            env.roc_io.onFatal();
        };

        // Store total size immediately before the user data pointer
        const size_ptr: *usize = @ptrFromInt(@intFromPtr(base_ptr) + size_storage_bytes - @sizeOf(usize));
        size_ptr.* = total_size;

        return @ptrFromInt(@intFromPtr(base_ptr) + size_storage_bytes);
    }

    /// Free memory previously allocated by `rocAlloc`.
    pub fn rocDealloc(roc_host: *RocHost, ptr: *anyopaque, alignment: usize) callconv(.c) void {
        const env: *RocEnv = @ptrCast(@alignCast(roc_host.env));
        const allocator = env.allocator;

        const min_alignment: usize = @max(alignment, @alignOf(usize));
        const align_enum = std.mem.Alignment.fromByteUnits(min_alignment);
        const size_storage_bytes = min_alignment;

        const size_ptr: *const usize = @ptrFromInt(@intFromPtr(ptr) - @sizeOf(usize));
        const total_size = size_ptr.*;

        const base_ptr: [*]u8 = @ptrFromInt(@intFromPtr(ptr) - size_storage_bytes);
        const slice = base_ptr[0..total_size];
        allocator.rawFree(slice, align_enum, @returnAddress());
    }

    /// Reallocate memory, copying existing data to the new allocation.
    pub fn rocRealloc(roc_host: *RocHost, ptr: *anyopaque, new_length: usize, alignment: usize) callconv(.c) ?*anyopaque {
        const env: *RocEnv = @ptrCast(@alignCast(roc_host.env));
        const allocator = env.allocator;

        const min_alignment: usize = @max(alignment, @alignOf(usize));
        const align_enum = std.mem.Alignment.fromByteUnits(min_alignment);
        const size_storage_bytes = min_alignment;

        // Read old size from metadata
        const old_size_ptr: *const usize = @ptrFromInt(@intFromPtr(ptr) - @sizeOf(usize));
        const old_total_size = old_size_ptr.*;
        const old_base_ptr: [*]u8 = @ptrFromInt(@intFromPtr(ptr) - size_storage_bytes);

        // Allocate new block
        const new_total_size = new_length + size_storage_bytes;
        const new_base_ptr = allocator.rawAlloc(new_total_size, align_enum, @returnAddress()) orelse {
            env.roc_io.writeStderr("roc_realloc: out of memory\n");
            env.roc_io.onFatal();
        };

        // Copy old user data to new location
        const old_user_data_size = old_total_size - size_storage_bytes;
        const copy_size = @min(old_user_data_size, new_length);
        const new_user_ptr: [*]u8 = @ptrFromInt(@intFromPtr(new_base_ptr) + size_storage_bytes);
        const old_user_ptr: [*]const u8 = @ptrCast(ptr);
        @memcpy(new_user_ptr[0..copy_size], old_user_ptr[0..copy_size]);

        // Free old allocation
        allocator.rawFree(old_base_ptr[0..old_total_size], align_enum, @returnAddress());

        // Store new size and return user pointer
        const new_size_ptr: *usize = @ptrFromInt(@intFromPtr(new_base_ptr) + size_storage_bytes - @sizeOf(usize));
        new_size_ptr.* = new_total_size;
        return new_user_ptr;
    }
};

/// Default handlers for dbg, expect-failed, and crash.
///
/// Routes output through `RocEnv.roc_io` for platform portability.
pub const DefaultHandlers = struct {
    /// Print a `dbg` expression to stderr.
    pub fn rocDbg(roc_host: *RocHost, bytes: [*]const u8, len: usize) callconv(.c) void {
        const env: *RocEnv = @ptrCast(@alignCast(roc_host.env));
        env.roc_io.writeStderr("[ROC DBG] ");
        env.roc_io.writeStderr(bytes[0..len]);
        env.roc_io.writeStderr("\n");
    }

    /// Print a failed `expect` to stderr.
    pub fn rocExpectFailed(roc_host: *RocHost, bytes: [*]const u8, len: usize) callconv(.c) void {
        const env: *RocEnv = @ptrCast(@alignCast(roc_host.env));
        env.roc_io.writeStderr("[ROC EXPECT] ");
        env.roc_io.writeStderr(bytes[0..len]);
        env.roc_io.writeStderr("\n");
    }

    /// Print a `crash` message to stderr and terminate.
    pub fn rocCrashed(roc_host: *RocHost, bytes: [*]const u8, len: usize) callconv(.c) void {
        const env: *RocEnv = @ptrCast(@alignCast(roc_host.env));
        env.roc_io.writeStderr("[ROC CRASHED] ");
        env.roc_io.writeStderr(bytes[0..len]);
        env.roc_io.writeStderr("\n");
        env.roc_io.onFatal();
    }
};

/// Create a host-internal helper context with default memory management and handlers.
///
/// This is only for helper functions in this generated file. It is not passed to
/// compiled Roc code, which uses the direct symbol ABI declared above.
///
/// Example:
/// ```zig
/// var env = RocEnv{ .allocator = gpa.allocator(), .roc_io = RocIo.default() };
/// var roc_host = makeRocHost(&env);
/// ```
pub fn makeRocHost(env: *RocEnv) RocHost {
    return .{
        .env = @ptrCast(env),
        .roc_alloc = &DefaultAllocators.rocAlloc,
        .roc_dealloc = &DefaultAllocators.rocDealloc,
        .roc_realloc = &DefaultAllocators.rocRealloc,
        .roc_dbg = &DefaultHandlers.rocDbg,
        .roc_expect_failed = &DefaultHandlers.rocExpectFailed,
        .roc_crashed = &DefaultHandlers.rocCrashed,
    };
}

// =============================================================================
// Provided Symbols
//
// Roc exports these symbols from the app with their natural C ABI signatures.
// =============================================================================

/// Entrypoint: init_for_host!
pub extern fn init_for_host() callconv(.c) RocBox;

/// Entrypoint: update_for_host!
pub extern fn update_for_host(arg0: RocBox) callconv(.c) RocBox;
