name: Tests

on:
  pull_request:
  workflow_dispatch:

# this cancels workflows currently in progress if you start a new one
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  test-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read Roc version
        id: pinned_roc
        shell: bash
        run: echo "nightly_tag=$(<.roc-version)" >> "$GITHUB_OUTPUT"

      - name: install Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0

      - name: Install Roc
        uses: roc-lang/setup-roc@main
        with:
          version: nightly-new-compiler
          nightly-tag: ${{ steps.pinned_roc.outputs.nightly_tag }}

      - run: roc version

      - run: ROC=roc ./ci/all_tests.sh
